version: '3.8'

services:
  web:
    
    build: .

    ports:
      - "8000:8000"
    
    volumes:
      - .:/app
   
    restart: unless-stopped
   
    command: venv/bin/waitress-serve --listen=0.0.0.0:8000 app:app